version: '3.1'

services:

  inventory_DB:
    image: mysql:latest
    container_name: inventory_DB
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sergey
      MYSQL_DATABASE: inventory_service
      MYSQL_USER: root_user
      MYSQL_PASSWORD: root_user
    networks:
      e-mart:

  order_DB:
    image: mysql:latest
    container_name: order_DB
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sergey
      MYSQL_DATABASE: order_service
      MYSQL_USER: root_user
      MYSQL_PASSWORD: root_user
    networks:
      e-mart:


  product_db:
    image: mongo
    restart: always
    container_name: mongo
    networks:
      - e-mart
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: products_service
      MONGODB_DATABASE: test1
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - product_db
    networks:
      - e-mart
    ports:
      - "8079:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27018
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - product_db


networks:
  e-mart:
