version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    networks:
      - e-mart
    ports:
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - e-mart
    ports:
      - 8079:8079
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:root@localhost:27018/


networks:
  e-mart:
