spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3307/order_service
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka