spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/product-service
      username: root
      password: root
  application:
    name: product-service


server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
