spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/product-service?authSource=admin
  application:
    name: product-service


server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      product:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: count_based
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      product:
        timeout-duration: 3s

  retry:
    instances:
      product:
        max-attempts: 10
        wait-duration: 5s






